### ISSUE TITLE
Enhanced data model deploy script has an error with the partial URL variable

### ISSUE THREAD

**Issue by asyedCS** [Cloudstrucc/Public#1]
$partialUrl = $name.ToLower()
  
this part of the code is causing issues when running as the error states that the partial URL for the home page needs to be "/" only and anything else is invalid

**Comment by Cloudstrucc** [comment]
@asyedCS script is fully tested, the root is based on the top level folder name which sets the home page as the parent to other webfiles and webpages (children)
